# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal9610/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gta4xlwifi gta4xl,$(TARGET_DEVICE)),)

include $(CLEAR_VARS)
LOCAL_MODULE := sswap
LOCAL_MODULE_OWNER := samsung
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT_SBIN)
LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_SBIN_UNSTRIPPED)
LOCAL_SRC_FILES := proprietary/rootfs/sbin/sswap
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

endif
